"use client"
import { useState } from "react"
import { useRouter } from "next/navigation"
import { Plus, Save, Loader2, MapPin, Printer, Edit3, Trash2, X, Check, AlertCircle } from "lucide-react"

const S={name:"Nooryi Studio",tag:"STUDIO FOR ARTISTS & EVENTS",reg:"123456789",tax:"300000000000003",web:"https://nooryi-studio.vercel.app"}

export default function PricingClient({artistId,artistSlug,artistName,regions}:{artistId:string;artistSlug:string;artistName:string;regions:any[]}){
  const router=useRouter();const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState("");const[editingId,setEditingId]=useState<string|null>(null);const[form,setForm]=useState({regionName:"",basePrice:"",travelFee:"0"})
  const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError("");try{const method=editingId?"PUT":"POST";const url=editingId?"/api/artists/"+artistSlug+"/pricing-regions/"+editingId:"/api/artists/"+artistSlug+"/pricing-regions";const res=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify({regionName:form.regionName,basePrice:parseFloat(form.basePrice),travelFee:parseFloat(form.travelFee)||0})});if(!res.ok){const d=await res.json();throw new Error(d.error||"فشل")}setSuccess(editingId?"تم التحديث ✅":"تم الإضافة ✅");setForm({regionName:"",basePrice:"",travelFee:"0"});setEditingId(null);router.refresh();setTimeout(()=>setSuccess(""),3000)}catch(err:any){setError(err.message)}finally{setSaving(false)}}
  const handleEdit=(r:any)=>{setEditingId(r.id);setForm({regionName:r.regionName,basePrice:String(r.basePrice),travelFee:String(r.travelFee||0)})}
  const handleDelete=async(id:string)=>{if(!confirm("حذف؟"))return;try{await fetch("/api/artists/"+artistSlug+"/pricing-regions/"+id,{method:"DELETE"});router.refresh();setSuccess("تم الحذف ✅");setTimeout(()=>setSuccess(""),3000)}catch(err:any){setError(err.message)}}
  const avg=regions.length>0?Math.round(regions.reduce((s,r)=>s+Number(r.basePrice),0)/regions.length):0
  const rn="PRC-"+artistSlug.toUpperCase().slice(0,6)+"-"+Date.now().toString(36).toUpperCase()
  const rd=new Date().toLocaleDateString("ar-EG",{year:"numeric",month:"long",day:"numeric"})
  const vu=S.web+"/verify/pricing/"+artistSlug+"?report="+rn

  const tRows=regions.map((r,i)=>{const tot=Number(r.basePrice)+Number(r.travelFee||0);return'<tr><td class="mono">'+String(i+1).padStart(2,'0')+'</td><td><div style="display:flex;align-items:center;gap:6px"><span style="color:#D4AF37">📍</span><span class="bold">'+r.regionName+'</span></div></td><td style="text-align:center;font-weight:700">'+Number(r.basePrice).toLocaleString()+' ج.م</td><td style="text-align:center;color:#666">'+(Number(r.travelFee||0)>0?"+"+Number(r.travelFee).toLocaleString()+" ج.م":"—")+'</td><td style="text-align:center"><span style="background:#D4AF37;color:#000;font-weight:900;padding:4px 12px;border-radius:6px;display:inline-block">'+tot.toLocaleString()+' ج.م</span></td></tr>'}).join("")

  const printHTML='<div class="page">'+
    '<div class="hdr"><div class="hdr-flex"><div><h1>Nooryi</h1><div class="gold-line"></div><p class="tagline">'+S.tag+'</p><div class="hdr-info"><p><b>السجل التجاري:</b> <code>'+S.reg+'</code></p><p><b>الرقم الضريبي:</b> <code>'+S.tax+'</code></p></div></div><div style="text-align:left"><div class="title-box"><h2>تقرير أسعار المناطق</h2><p>'+artistName+'</p></div><div class="rid"><div class="rl">رقم التقرير</div><div class="rv">'+rn+'</div></div></div></div></div>'+
    '<div class="content">'+
    '<div class="asec"><div class="acard"><div class="al">الفنان:</div><div class="ainfo"><div class="aph">'+artistName.charAt(0)+'</div><div><div class="an">'+artistName+'</div><div class="acat">'+(regions.length)+' منطقة مسجلة</div></div></div></div><div style="text-align:left;display:flex;align-items:center"><div class="dg"><span class="dl">تاريخ الإصدار:</span><span class="dv">'+rd+'</span><span class="dl">عدد المناطق:</span><span class="dv">'+regions.length+'</span><span class="dl">متوسط السعر:</span><span class="dv">'+avg.toLocaleString()+' ج.م</span><span class="dl">العملة:</span><span class="dv">EGP</span></div></div></div>'+
    '<div class="stitle">تفاصيل الأسعار حسب المنطقة</div>'+
    (regions.length===0?'<p style="text-align:center;color:#888;padding:30px">لا توجد مناطق مسجلة</p>':'<table class="tbl"><thead><tr><th style="text-align:right">#</th><th style="text-align:right">المنطقة</th><th style="text-align:center">السعر الأساسي</th><th style="text-align:center">رسوم السفر</th><th style="text-align:center">الإجمالي</th></tr></thead><tbody>'+tRows+'</tbody><tfoot><tr style="background:#0a0a0a;color:#D4AF37;font-weight:900"><td colspan="2" style="text-align:right;padding:10px">المجموع</td><td style="text-align:center;padding:10px">'+regions.reduce((s,r)=>s+Number(r.basePrice),0).toLocaleString()+' ج.م</td><td style="text-align:center;padding:10px">'+regions.reduce((s,r)=>s+Number(r.travelFee||0),0).toLocaleString()+' ج.م</td><td style="text-align:center;padding:10px">'+regions.reduce((s,r)=>s+Number(r.basePrice)+Number(r.travelFee||0),0).toLocaleString()+' ج.م</td></tr></tfoot></table>')+
    '</div>'+
    '<div class="ftr"><div class="ftr-grid"><div class="ftr-left"><h4>الشروط والأحكام:</h4><ul><li><span class="dot">•</span>الأسعار قابلة للتغيير دون إشعار مسبق.</li><li><span class="dot">•</span>رسوم السفر تُضاف تلقائياً حسب منطقة الفعالية.</li><li><span class="dot">•</span>يمكن التحقق بمسح رمز QR أدناه.</li></ul></div><div class="stamp-col"><div class="stamp"><div class="stamp-ring"></div><div class="stamp-txt"><div class="s1">NOORYI</div><div class="sline"></div><div class="s2">STUDIO</div><div class="s3">✓ معتمد رسمياً</div></div></div><div class="stamp-label">ختم المنصة الرسمي</div></div><div class="qr-col"><div class="qr-box"><img src="https://api.qrserver.com/v1/create-qr-code/?size=80x80&data='+encodeURIComponent(vu)+'" width="80" height="80"/></div><div class="qr-label">امسح للتحقق من صحة التقرير</div></div></div><div class="sig"><div class="sig-line"></div><div class="sig-name">توقيع المدير المالي</div><div class="sig-dept">Nooryi Studio Finance Dept.</div></div><div class="copyright">© '+new Date().getFullYear()+' '+S.name+' — جميع الحقوق محفوظة</div></div>'+
  '</div>'

  const handlePrint=()=>{const win=window.open("","_blank","width=800,height=1100");if(!win){alert("اسمح بالنوافذ المنبثقة");return}win.document.write('<!DOCTYPE html><html dir="rtl" lang="ar"><head><meta charset="UTF-8"><title>أسعار '+artistName+'</title><style>'+$HEADER_CSS+'</style></head><body>'+printHTML+'</body></html>');win.document.close();setTimeout(()=>win.print(),800)}

  return(
    <div dir="rtl" className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div><div className="badge-gold mb-3">التسعير</div><h1 className="text-3xl font-black text-white flex items-center gap-2"><MapPin size={28} className="text-[#D4AF37]"/> تسعير {artistName}</h1><p className="text-gray-400 text-sm mt-1">{regions.length} منطقة • متوسط: {avg.toLocaleString()} ج.م</p></div>
        <button onClick={handlePrint} disabled={regions.length===0} className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-[#D4AF37] to-[#b8941f] text-[#0a0a0a] rounded-xl font-black text-sm hover:shadow-lg transition disabled:opacity-50"><Printer size={16}/> طباعة</button>
      </div>
      {error&&<div className="bg-red-500/10 border border-red-500/30 rounded-xl p-4 text-red-400 font-bold flex items-center gap-2"><AlertCircle size={20}/>{error}</div>}
      {success&&<div className="bg-green-500/10 border border-green-500/30 rounded-xl p-4 text-green-400 font-bold flex items-center gap-2"><Check size={20}/>{success}</div>}
      <div className="bg-[#111] rounded-2xl border border-[#D4AF37]/20 overflow-hidden"><div className="p-5 border-b border-[#D4AF37]/20"><h2 className="text-xl font-black text-white">مناطق التسعير</h2></div>{regions.length===0?<p className="text-gray-500 text-center py-10">لا توجد مناطق</p>:<div className="overflow-x-auto"><table className="w-full min-w-[600px]"><thead><tr className="border-b border-[#D4AF37]/20 bg-[#0a0a0a]"><th className="text-right py-3 px-4 text-xs font-bold text-[#D4AF37] uppercase">المنطقة</th><th className="text-center py-3 px-4 text-xs font-bold text-[#D4AF37] uppercase">السعر</th><th className="text-center py-3 px-4 text-xs font-bold text-[#D4AF37] uppercase">السفر</th><th className="text-center py-3 px-4 text-xs font-bold text-[#D4AF37] uppercase">الإجمالي</th><th className="text-center py-3 px-4 text-xs font-bold text-[#D4AF37] uppercase">إجراءات</th></tr></thead><tbody>{regions.map(r=>(<tr key={r.id} className="border-b border-[#D4AF37]/5 hover:bg-[#1a1a1a]"><td className="py-3 px-4 font-bold text-white">{r.regionName}</td><td className="py-3 px-4 text-center text-gray-300">{Number(r.basePrice).toLocaleString()} ج.م</td><td className="py-3 px-4 text-center text-gray-400">{Number(r.travelFee||0).toLocaleString()} ج.م</td><td className="py-3 px-4 text-center font-black text-[#D4AF37]">{(Number(r.basePrice)+Number(r.travelFee||0)).toLocaleString()} ج.م</td><td className="py-3 px-4 text-center"><div className="flex items-center justify-center gap-2"><button onClick={()=>handleEdit(r)} className="p-2 bg-blue-500/10 hover:bg-blue-500/20 rounded-lg text-blue-400 transition"><Edit3 size={14}/></button><button onClick={()=>handleDelete(r.id)} className="p-2 bg-red-500/10 hover:bg-red-500/20 rounded-lg text-red-400 transition"><Trash2 size={14}/></button></div></td></tr>))}</tbody></table></div>}</div>
      <div className="bg-[#111] rounded-2xl border border-[#D4AF37]/20 p-5"><h3 className="text-lg font-black text-white mb-4 flex items-center gap-2"><Plus size={18} className="text-[#D4AF37]"/>{editingId?"تعديل المنطقة":"إضافة منطقة جديدة"}</h3><form onSubmit={handleSubmit} className="space-y-4"><div className="grid md:grid-cols-3 gap-4"><div><label className="block text-xs font-bold text-gray-400 mb-1">اسم المنطقة *</label><input type="text" value={form.regionName} onChange={e=>setForm({...form,regionName:e.target.value})} placeholder="القاهرة" className="w-full px-4 py-3 bg-[#1a1a1a] border border-[#D4AF37]/20 rounded-xl text-white outline-none focus:ring-2 focus:ring-[#D4AF37]" required/></div><div><label className="block text-xs font-bold text-gray-400 mb-1">السعر (ج.م) *</label><input type="number" value={form.basePrice} onChange={e=>setForm({...form,basePrice:e.target.value})} placeholder="5000" className="w-full px-4 py-3 bg-[#1a1a1a] border border-[#D4AF37]/20 rounded-xl text-white outline-none focus:ring-2 focus:ring-[#D4AF37]" required/></div><div><label className="block text-xs font-bold text-gray-400 mb-1">رسوم السفر</label><input type="number" value={form.travelFee} onChange={e=>setForm({...form,travelFee:e.target.value})} placeholder="0" className="w-full px-4 py-3 bg-[#1a1a1a] border border-[#D4AF37]/20 rounded-xl text-white outline-none focus:ring-2 focus:ring-[#D4AF37]"/></div></div><div className="flex gap-3"><button type="submit" disabled={saving} className="flex-1 py-3 bg-gradient-to-r from-[#D4AF37] to-[#b8941f] text-[#0a0a0a] font-black rounded-xl disabled:opacity-50 flex items-center justify-center gap-2">{saving?<><Loader2 size={18} className="animate-spin"/> جاري...</>:<><Save size={18}/> {editingId?"تحديث":"إضافة"}</>}</button>{editingId&&<button type="button" onClick={()=>{setEditingId(null);setForm({regionName:"",basePrice:"",travelFee:"0"})}} className="px-6 py-3 bg-[#1a1a1a] border border-[#D4AF37]/20 rounded-xl font-bold text-gray-400 hover:text-white transition"><X size={18}/></button>}</div></form></div>
    </div>
  )
}